apiVersion: v1
kind: Service
metadata:
  name: hari
  
  namespace: jenkins
  
  labels:
    run: hari
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
    name: http
 
  selector:
    run: hari
